### ISSUE TITLE
Theme not loaded

### ISSUE THREAD

**Issue by ghost** [ronisbr/doom-nano-themes#2]
Hi @ronisbr , 
this is a great approach bringing NANO to Doom Emacs, however I am not able loading the theme.
I tried various with various attempts:

1) As described, putting the files to the folder `.doom.d/themes/`.
This folder did not exist yet and I had to create it.
As soon as I inserted `(setq doom-theme 'doom-nano-dark)` into the `config.el` file and reloaded Emacs I got a blank screen.

2) Similar to #1 .

In my `packages.el` file I inserted

```
(package! doom-nano-modeline
  :recipe (:host github :repo "ronisbr/doom-nano-modeline"))

(package! doom-nano-themes
  :recipe (:host github :repo "ronisbr/doom-nano-themes"))
```
and then I reloaded Doom Emacs (`SPC h r r`). I did see that the two packages got downloaded and installed, but the theme is not in the Doom themes overview and when I try to load it with `(setq doom-theme 'doom-nano-dark)` from the `config.el` file I get a blank screen again.

**Comment by tapir2342** [comment]
This also happens to me. I just downloaded the files and put them in `.doom.d/themes`. Emacs is just completely black.

**Comment by shartf** [comment]
I've also got the same issue, but it was fixed after I've added config for modeline to config.el: 
`(use-package! doom-nano-modeline
  :config
  (doom-nano-modeline-mode 1)
  (global-hide-mode-line-mode 1))`

I think it is actually required somehow, but the instructions for the theme are not clear on that.

**Comment by ronisbr** [comment]
Hum, let me try the theme without the mode-line.

**Comment by ronisbr** [comment]
Doom Emacs without the Doom-nano-modeline is working here for those themes. Is there any error message? What is your environment? I have no clue what is going on.

<img width="800" alt="Captura de Tela 2023-02-26 às 11 05 22" src="https://user-images.githubusercontent.com/1068295/221415373-025c4013-945c-4a73-9d16-0f4dddee8632.png">

**Comment by ronisbr** [comment]
~~@LukasCBossert can you please remove the entry in `packages.el` related to `doom-nano-themes`? It is not supposed to download this theme using `use-package`. You really need to copy the files to `themes` until I find a better solution.~~

Sorry, I managed to reproduce. If you set the theme by default in `config.el`, it starts blank. It works if you start with another theme and then load using `M-x load-theme`.

**Comment by ronisbr** [comment]
Done! Thanks for the bug report! Since this theme is not inside `doom-themes`, using only `setq` to set it will not work. We need to load the theme after `doom-themes` is loaded. Hence, you need to add in `config.el`:

```
(after! doom-themes
  (load-theme 'doom-nano-light t))
```

I updated the README.md. Please, let me know if it is working now.

**Comment by ghost** [comment]
@ronisbr , great - it now works! Thanks for the very quick support!
