### ISSUE TITLE
Header bar not shown

### ISSUE THREAD

**Issue by ghost** [ronisbr/doom-nano-themes#3]
With my current setup I do not get the header bar as in your screenshot
<img width="961" alt="Screenshot 2023-02-27 at 23 51 45" src="https://user-images.githubusercontent.com/12896078/221705367-a7bc4f88-d665-4b1f-8362-17f9be2dc8a9.png">

I have a blank line instead:
<img width="908" alt="Screenshot 2023-02-27 at 23 49 04" src="https://user-images.githubusercontent.com/12896078/221705576-d0ed818b-690b-4b2c-be01-1393295035a5.png">

Does my `init.el`-file taking effect on it?

**Comment by ronisbr** [comment]
Hi @LukasCBossert !

Did you install `doom-nano-modeline`?

If so, this happens if there is an error when generating the decorated string of the modeling. Can you please run `(doom-nano-modeline-default-mode)` and check if there is any error?

**Comment by ghost** [comment]
Hi @ronisbr ,

`(doom-nano-modeline-default-mode)` is enabled and in my message-buffer I see this
```
Error during redisplay: (eval (funcall (or (catch 'found (dolist (elt doom-nano-modeline-mode-formats) (let* ((config (cdr elt)) (mode-p (plist-get config :mode-p)) (format (plist-get config :format))) (when mode-p (when (funcall mode-p) (throw 'found format)))))) #'doom-nano-modeline-default-mode-format))) signaled (wrong-number-of-arguments #<subr mapconcat> 2) [8 times]
```

does this help?


For the sake of completeness:

In my `config.el` I have:

```
(after! doom-themes
  (load-theme 'doom-nano-dark t)
  )

(use-package! doom-nano-modeline
  :config
  (doom-nano-modeline-mode 1)
  (global-hide-mode-line-mode 1)
  )
```

in the `packages.el`:
```
(package! doom-nano-modeline
  :recipe (:host github
  :repo "ronisbr/doom-nano-modeline"))
```

and the two theme-files are in my `.doom.d/themes/`-folder.

**Comment by ronisbr** [comment]
Everything is right in your configuration. I have no idea why we are having this problem in `mapconcat` function. What is you Emacs version?

**Comment by ghost** [comment]
`GNU Emacs 28.2 (build 1, aarch64-apple-darwin21.6.0, Carbon Version 165 AppKit 2113.6) of 2022-09-15`

**Comment by ronisbr** [comment]
Is it blank in every file? For example, try opening a C++ file.

**Comment by ghost** [comment]
yes, each file is affected. Regardless of the type.

**Comment by ghost** [comment]
Did you have any time to look into this or any idea what I could do, @ronisbr ?

**Comment by ronisbr** [comment]
Is it possible to try in a fresh doom section? For example, delete .doom.d, .emacs.d, add doom-nano-themes and doom-nano-modeline, and try again?

**Comment by ghost** [comment]
I did a complete new installation and only added the doom-nano-themes and and the doom-nano-modeline (as written above).

Still same error:
```
Error during redisplay: (eval (funcall (or (catch 'found (dolist (elt doom-nano-modeline-mode-formats) (let* ((config (cdr elt)) (mode-p (plist-get config :mode-p)) (format (plist-get config :format))) (when mode-p (when (funcall mode-p) (throw 'found format)))))) #'doom-nano-modeline-default-mode-format))) signaled (wrong-number-of-arguments #<subr mapconcat> 2) [99 times]
```



My `doom-info` is:
```
generated  Mar 03, 2023 01:24:29
system     MacOS 13.2.1 Darwin 22.3.0 arm64 mac
emacs      28.2 ~/.config/emacs/
doom       3.0.0-pre PROFILE=_@0 grafted, HEAD -> master, origin/master, origin/HEAD
           8f6b045 2023-03-01 17:32:32 -0500 ~/.config/doom/
shell      /bin/zsh
features   ACL GMP GNUTLS JSON LIBXML2 MODULES NOTIFY KQUEUE PDUMPER THREADS
           TOOLKIT_SCROLL_BARS XIM ZLIB
traits     gui server-running envvar-file
modules    :config use-package :completion company vertico :ui doom doom-dashboard
           hl-todo modeline ophints (popup +defaults) (vc-gutter +pretty)
           vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold
           snippets :emacs dired electric undo vc :checkers syntax :tools (eval
           +overlay) lookup magit :os macos :lang emacs-lisp markdown org sh :config
           (default +bindings +smartparens)
packages   (doom-nano-modeline :recipe (:host github :repo
           ronisbr/doom-nano-modeline))
```

**Comment by ronisbr** [comment]
I am using Emacs 29. I will install 28 to check if there is some compatibility issue.

**Comment by ghost** [comment]
I dont mind upgrading if this helps.... (if you tell me how to do best using homebrew).

**Comment by ghost** [comment]
Ok, I installed emacs 29 now and it works!!!!!

**Comment by ronisbr** [comment]
Wow! Thanks! Probably the function `mapreduce` changed the API! I need to verify how can I support Emacs 28.

**Comment by ronisbr** [comment]
I found the problem! The last argument in `mapconcat` in Emacs 28 is not optional! It should now be fixed by https://github.com/ronisbr/doom-nano-modeline/commit/14a6adb28e06c383c351c1823237abaddfbab4d1

Can you please test in Emacs 28?

**Comment by ghost** [comment]
oh - I deleted my Emacs 28 completely......

**Comment by ronisbr** [comment]
No problem! I will test later :) Thanks!
