### ISSUE TITLE
Minor visual bug(?) involving workspaces

### ISSUE THREAD

**Issue by fosskers** [ronisbr/doom-nano-themes#4]
Thanks for a beautiful theme!

I noticed an issue just now: when you hit `SPC TAB TAB` to view the current workspaces, normally the current workspace is highlighted. With `doom-nano-theme-dark`, there doesn't seem to be a highlight. Any clue as to what might be happening here?

Cheers, and thank you.

**Comment by ronisbr** [comment]
Hi @fosskers !

Indeed, I just need to figure out what is the font face used at this stage to fix the problem.

**Comment by ronisbr** [comment]
I think I could fix it! Can you please test @fosskers ?

**Comment by fosskers** [comment]
Yup, that change makes it clear which workspace is current. Thank you!
